CREATE DATABASE IF NOT EXISTS T1_DSW1;
USE T1_DSW1;

CREATE TABLE IF NOT EXISTS Usuario (
    id INT AUTO_INCREMENT NOT NULL,
    documento VARCHAR(20) UNIQUE NOT NULL,
    email VARCHAR(256) NOT NULL,
    senha VARCHAR(256) NOT NULL,
    nome VARCHAR(256) NOT NULL,
    isAdmin BOOLEAN DEFAULT false,
    isLocadora BOOLEAN NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS Cliente (
    id_usuario INT NOT NULL,
    CPF VARCHAR(11) UNIQUE NOT NULL,
    telefone VARCHAR(20) NOT NULL,
    sexo VARCHAR(2) NOT NULL,
    data_nascimento DATE NOT NULL,
    PRIMARY KEY (CPF),
    FOREIGN KEY (id_usuario) REFERENCES Usuario (id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS Locadora (
  id_locadora INT NOT NULL,
  CNPJ CHAR(14) NOT NULL,
  cidade VARCHAR(256) NOT NULL,
  PRIMARY KEY (CNPJ),
  FOREIGN KEY (id_locadora) REFERENCES Usuario (id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS Locacao (
  CPF CHAR(11) NOT NULL,
  CNPJ CHAR(14) NOT NULL,
  dia DATE NOT NULL,
  horario TIME NOT NULL,
  PRIMARY KEY (CNPJ, dia, horario),
  FOREIGN KEY (CPF) REFERENCES Cliente (CPF) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (CNPJ) REFERENCES Locadora (CNPJ) ON DELETE CASCADE ON UPDATE CASCADE
);